#!/bin/sh

# Set these paths appropriately

BIN="/var/www/html/moodle/local/similarity/treeTagger/bin"
CMD="/var/www/html/moodle/local/similarity/treeTagger/cmd"
LIB="/var/www/html/moodle/local/similarity/treeTagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
MWL=${CMD}/greek-mwls.pl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/greek-abbreviations
PARFILE=${LIB}/greek.par

$TOKENIZER -a $ABBR_LIST $* |
$MWL |
# tagging
$TAGGER $OPTIONS $PARFILE

