#!/bin/sh

# Set these paths appropriately

BIN="/var/www/html/moodle/local/similarity/treeTagger/bin"
CMD="/var/www/html/moodle/local/similarity/treeTagger/cmd"
LIB="/var/www/html/moodle/local/similarity/treeTagger/lib"

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovenian.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
