#!/bin/sh

# Set these paths appropriately

BIN="/var/www/html/moodle/local/similarity/treeTagger/bin"
CMD="/var/www/html/moodle/local/similarity/treeTagger/cmd"
LIB="/var/www/html/moodle/local/similarity/treeTagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
