#!/bin/sh

# Set these paths appropriately

BIN="/var/www/html/moodle/local/similarity/treeTagger/bin"
CMD="/var/www/html/moodle/local/similarity/treeTagger/cmd"
LIB="/var/www/html/moodle/local/similarity/treeTagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/swahili-abbreviations
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/swahili.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
