#!/bin/sh

# Set these paths appropriately

BIN="/var/www/html/moodle/local/similarity/treeTagger/bin"
CMD="/var/www/html/moodle/local/similarity/treeTagger/cmd"
LIB="/var/www/html/moodle/local/similarity/treeTagger/lib"

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize-korean.pl
PARFILE=${LIB}/korean.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE |
$CMD/add-korean-sentence-markers.pl |
$CMD/reformat-korean-tagger-output.pl
